package tony.project.language.domain;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.document.ItemCollection;
import com.amazonaws.services.dynamodbv2.document.ScanOutcome;

import tony.project.language.interfaces.StaffDAO;

@DynamoDBTable(tableName="Staff")
public class Staff extends RootObject<Staff> implements StaffDAO {

	private String StaffID;
	private String AccountName;
	private String PrivateEmail;
	private String Password;
	
	@DynamoDBHashKey(attributeName="StaffID")
	@DynamoDBAutoGeneratedKey
	public String getStaffID() {return StaffID;}
	public void setStaffID(String staffID) {StaffID = staffID;}

	@DynamoDBIndexHashKey(globalSecondaryIndexName="AccountName-index")
	public String getAccountName() {return AccountName;}
	public void setAccountName(String accountName) {AccountName = accountName;}

	@DynamoDBAttribute(attributeName="PrivateEmail")
	public String getPrivateEmail() {return PrivateEmail;}
	public void setPrivateEmail(String privateEmail) {PrivateEmail = privateEmail;}

	@DynamoDBAttribute(attributeName="Password")
	public String getPassword() {return Password;}
	public void setPassword(String password) {Password = password;}

	
	@Override
	public void saveStaff(Staff user) {

		save(user);
		
	}

	@Override
	public ItemCollection<ScanOutcome> getStaff(String accountName) {
		
		return load(accountName);
	}

	@Override
	public void updateStaff(String emailAddress, String passWord) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void updateStaffEmail(String emailAddress) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void deleteStaff(String hashKey) {

		deleteByMapper(hashKey);
	}

	public Staff(String staffID, String accountName, String privateEmail, String password) {
		super();
		StaffID = staffID;
		AccountName = accountName;
		PrivateEmail = privateEmail;
		Password = password;
	}
	public Staff(String accountName, String privateEmail, String password) {
		super();
		AccountName = accountName;
		PrivateEmail = privateEmail;
		Password = password;
	}

	public Staff() {
		super();
	}
	@Override
	public String toString() {
		return "Staff [StaffID=" + StaffID + ", AccountName=" + AccountName + ", PrivateEmail=" + PrivateEmail
				+ ", Password=" + Password + "]";
	}

	

	
	
	
}
